[package]
name = "sqlink"
version = "0.6.0"
authors = ["Liam <nghenglim@gmail.com>"]
edition = "2018"
description = "postgres builder to work with postgres"
license = "MIT/Apache-2.0"

[features]
default = []

[dependencies]
postgres-types = "0.1"
