name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: rustup update && cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build integrated
      run: cd sqlink-test && cargo build --verbose
    - name: Test integrated
      run: cd sqlink-test && docker-compose up --detach && cargo test --verbose
